import {TitleAndDescription} from "./title-and-description";
import {MenuItemBulletList} from "./menu-item-bullet-list";
import {MenuItemCatalogGroup} from "./menu-item-catalog-group";
import {MenuItemBook} from "./menu-item-book";
import {Tag} from "./tag";
import {Image} from "./image";
import {PDFLink} from "./pdf_link";
import {FormField} from "./form-field";
import {PromotionHeader} from "./promotion-header";

export class MenuItem {
    id: number;
    menu_section_id: number;
    menu_category_id: number;
    hotel_id: number;
    name: string;
    description: string;
    image_url: string;
    email: string;
    phone: string;
    youtube: string;
    web_site_title: string;
    web_site_url: string;
    virtual_tour_url: string;
    dress_code: string;
    location_description: string;
    activate_map_location: boolean;
    map_location: string;
    map_location_point_icon: string;
    show_title_and_description: boolean;
    show_bullet_list: boolean;
    show_dress_code: boolean;
    show_location_description: boolean;
    show_email: boolean;
    show_phone_number: boolean;
    show_youtube: boolean;
    show_web_site: boolean;
    show_virtual_tour: boolean;
    booking_system: string;
    external_booking_engine_url: string;
    emails_of_the_staff: string;
    see_more: boolean;
    see_more_menu_section_id: number;
    show_follow: boolean;
    show_booking_date: boolean;
    show_loyalty_point: boolean;
    loyalty_min_point: number;
    loyalty_max_point: number;
    show_survey: boolean;
    survey_title: string;
    survey_description: string;
    priority: number;
    child_count: number;
    adult_count: number;
    baby_count: number;
    url_links: string;
    url_title: string;
    auto_approve: boolean;
    photos: string;
    fix_menu: boolean;
    active: boolean;
    show_on_home_page: boolean;
    location_control_mandatory: boolean;
    user_ids_for_notifications: string;
    room_capacity: number;
    min_accomodation: number;
    bed_count: number;
    number_of_bedroom: number;
    bath_count: number;
    field: number;
    base_price: number;
    menu_item_title_and_descriptions: TitleAndDescription[] | null;
    menu_item_bullet_lists: MenuItemBulletList[] | null;
    menu_item_catalog_groups: MenuItemCatalogGroup[] | null;
    menu_item_books: MenuItemBook[] | null;
    tags: Tag[] | null;
    images: Image[] | null;
    videos: Image[] | null;
    pdf_links: PDFLink[] | null;
    form_fields: FormField[];
    order_system: boolean;
    show_price: boolean;
    show_comment: boolean;
    show_order_info: boolean;
    only_table: boolean;

    promotions: PromotionHeader[];

    activate_delivery_range: boolean;
    delivery_range: number;
    activate_delivery_post_codes: boolean;
    delivery_post_codes: string;
    activate_excluded_post_codes: boolean;
    excluded_post_codes: string;
    activate_free_delivery_over_amount: boolean;
    free_delivery_over_amount: number;
    delivery_price_distance_range_1: number;
    delivery_price_type_1: 'fix' | 'distance';
    delivery_unit_price_1: number;
    delivery_price_distance_range_2: number;
    delivery_price_type_2: 'fix' | 'distance';
    delivery_unit_price_2: number;
    delivery_price_distance_range_3: number;
    delivery_price_type_3: 'fix' | 'distance';
    delivery_unit_price_3: number;
    show_date_range: boolean;
    start_date: Date;
    end_date: Date;
    end_time: string;
}
